"""Build docs/learning/coach.html from the sweep JSON — VRAG-018.

    make coach

The coach page is the primer's other half: the primer argues, the page lets you move the
lever and read what actually happened. Both are backed by the same file,
`docs/learning/data/chunking_sweep.json`, written by `tools/sweep_chunking.py`.

Why a builder instead of a hand-written page
--------------------------------------------
Two reasons, and neither is convenience.

**No number on the page is typed by a human.** Every figure is read out of the sweep JSON at
build time. Re-run `make sweep` after moving an ASR arm or an embedding model and `make
coach` re-renders against the new measurements; a hand-maintained page would keep showing
last week's recall next to this week's config and nothing would flag it.

**The page has to open off the filesystem.** `web/index.html` is served by `src.api` and can
fetch; this one is opened by double-clicking, and `fetch('data/chunking_sweep.json')` from a
`file://` page is blocked by the browser's origin rules. So the JSON is inlined into a
`<script type="application/json">` block here, at build time.

What does not go on the page: chunk text. The sweep JSON holds counts only
(`data/corpus/PROVENANCE.md` — Video-MME text is not redistributable) and this script copies
it verbatim, so the page inherits that property rather than restating it.
"""

from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SWEEP = ROOT / "docs" / "learning" / "data" / "chunking_sweep.json"
OUT = ROOT / "docs" / "learning" / "coach.html"

TEMPLATE = r"""<!doctype html>
<!--
  GENERATED by tools/build_coach.py — edit that, not this. `make coach` rebuilds it.

  The VRAG-018 coach page. Every number here is read from the sweep JSON inlined below,
  which tools/sweep_chunking.py wrote; nothing on this page is typed by hand.

  Standalone on purpose: no server, no build step, no fetch. A file:// page cannot fetch its
  own data directory, so the measurements are inlined rather than loaded.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VRAG coach — chunking, embeddings, and what overlap costs</title>
<meta name="description" content="Move the chunking levers and read the recall, the index size and the duplication that were actually measured on evals/dev.">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><text y='26' font-size='24' font-family='system-ui' font-weight='700'>55</text></svg>">
<style>
:root {
  --brand: #e2402c;
  --brand-soft: color-mix(in srgb, var(--brand) 12%, transparent);
  --bg: #fbfbfa;
  --panel: #ffffff;
  --ink: #17171a;
  --ink-2: #5a5a63;
  --ink-3: #8b8b95;
  --line: #e7e7e4;
  --line-2: #f1f1ee;
  --ok: #1a9c62;
  --warn: #c98a00;
  --radius: 14px;
  --font: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Inter, Roboto, sans-serif;
  --mono: ui-monospace, SFMono-Regular, "Cascadia Mono", Menlo, Consolas, monospace;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0e0e11; --panel: #17171b; --ink: #f2f2f0; --ink-2: #a6a6b0; --ink-3: #71717c;
    --line: #26262c; --line-2: #1e1e23; --ok: #3ecf8e; --warn: #e0aa2e;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--ink); font-family: var(--font);
  line-height: 1.55; -webkit-text-size-adjust: 100%;
}
.wrap { max-width: 60rem; margin: 0 auto; padding: 2rem 1.25rem 5rem; }
header.top { border-bottom: 1px solid var(--line); padding-bottom: 1.5rem; margin-bottom: 2rem; }
.mark {
  display: inline-grid; place-items: center; width: 2rem; height: 2rem; border-radius: 8px;
  background: var(--brand); color: #fff; font-weight: 700; font-size: .85rem;
}
h1 { font-size: 1.6rem; line-height: 1.25; margin: .9rem 0 .4rem; letter-spacing: -.01em; }
h2 { font-size: 1.15rem; margin: 2.75rem 0 .5rem; letter-spacing: -.01em; }
h3 { font-size: .95rem; margin: 1.5rem 0 .4rem; }
p { margin: .6rem 0; color: var(--ink-2); }
p.lede { color: var(--ink); font-size: 1.02rem; }
code, .mono { font-family: var(--mono); font-size: .87em; }
code { background: var(--line-2); padding: .1em .35em; border-radius: 5px; }
a { color: var(--brand); }
.prov {
  display: flex; flex-wrap: wrap; gap: .4rem .5rem; margin-top: 1rem;
  font-family: var(--mono); font-size: .74rem; color: var(--ink-3);
}
.prov span { border: 1px solid var(--line); border-radius: 999px; padding: .15rem .55rem; }
.panel {
  background: var(--panel); border: 1px solid var(--line); border-radius: var(--radius);
  padding: 1.1rem 1.2rem; margin: 1rem 0;
}
.levers { display: grid; grid-template-columns: repeat(auto-fit, minmax(15rem, 1fr)); gap: 1.25rem; }
.lever label { display: block; font-size: .78rem; text-transform: uppercase;
  letter-spacing: .06em; color: var(--ink-3); margin-bottom: .35rem; }
.lever .val { font-family: var(--mono); font-size: 1.35rem; color: var(--ink); }
.lever input[type=range] { width: 100%; accent-color: var(--brand); margin-top: .4rem; }
.ticks { display: flex; justify-content: space-between; font-family: var(--mono);
  font-size: .68rem; color: var(--ink-3); }
.readout { display: grid; grid-template-columns: repeat(auto-fit, minmax(8.5rem, 1fr));
  gap: .1rem; margin-top: 1.25rem; border-top: 1px solid var(--line); padding-top: 1rem; }
.stat { padding: .5rem .1rem; }
.stat .k { font-size: .7rem; text-transform: uppercase; letter-spacing: .06em; color: var(--ink-3); }
.stat .v { font-family: var(--mono); font-size: 1.15rem; margin-top: .15rem; }
.stat .n { font-size: .72rem; color: var(--ink-3); }
.stat[data-flag="good"] .v { color: var(--ok); }
.stat[data-flag="warn"] .v { color: var(--warn); }
.stat[data-flag="bad"] .v { color: var(--brand); }
.note {
  margin-top: 1rem; padding: .7rem .85rem; border-radius: 10px; font-size: .85rem;
  border: 1px solid var(--line); background: var(--line-2); color: var(--ink-2);
}
.note[data-kind="shipped"] { border-color: color-mix(in srgb, var(--ok) 40%, var(--line));
  background: color-mix(in srgb, var(--ok) 8%, transparent); }
.note[data-kind="unmeasured"] { border-color: color-mix(in srgb, var(--warn) 45%, var(--line));
  background: color-mix(in srgb, var(--warn) 10%, transparent); }
figure { margin: 1.25rem 0 0; }
figcaption { font-size: .8rem; color: var(--ink-3); margin-top: .5rem; }
svg { display: block; width: 100%; height: auto; overflow: visible; }
.chart-line { fill: none; stroke: var(--brand); stroke-width: 2; }
.chart-dot { fill: var(--brand); }
.chart-dot.shipped { stroke: var(--ink); stroke-width: 2; }
.chart-bar { fill: color-mix(in srgb, var(--ink) 14%, transparent); }
.chart-axis { stroke: var(--line); stroke-width: 1; }
.chart-thresh { stroke: var(--ok); stroke-width: 1; stroke-dasharray: 4 3; }
.chart-label { fill: var(--ink-3); font-family: var(--mono); font-size: 10px; }
.chart-value { fill: var(--ink-2); font-family: var(--mono); font-size: 10px; text-anchor: middle; }
.scroll { overflow-x: auto; }
table { border-collapse: collapse; width: 100%; font-size: .84rem; min-width: 44rem; }
th, td { text-align: right; padding: .4rem .55rem; border-bottom: 1px solid var(--line-2);
  font-family: var(--mono); white-space: nowrap; }
th { color: var(--ink-3); font-weight: 600; font-size: .72rem; text-transform: uppercase;
  letter-spacing: .05em; border-bottom-color: var(--line); }
th:first-child, td:first-child { text-align: left; }
tr[data-shipped="1"] td { background: color-mix(in srgb, var(--ok) 9%, transparent); }
tr[data-cut="overlap"] td:first-child { color: var(--ink-3); }
ol.checks { counter-reset: c; list-style: none; padding: 0; margin: 1rem 0 0; }
ol.checks > li {
  counter-increment: c; position: relative; padding: .9rem 0 .9rem 2.6rem;
  border-top: 1px solid var(--line);
}
ol.checks > li::before {
  content: counter(c); position: absolute; left: 0; top: .95rem;
  display: grid; place-items: center; width: 1.7rem; height: 1.7rem; border-radius: 50%;
  background: var(--brand-soft); color: var(--brand); font-family: var(--mono);
  font-size: .8rem; font-weight: 700;
}
ol.checks strong { color: var(--ink); font-weight: 600; }
pre {
  background: var(--line-2); border: 1px solid var(--line); border-radius: 10px;
  padding: .6rem .8rem; overflow-x: auto; font-family: var(--mono); font-size: .8rem;
  color: var(--ink); margin: .5rem 0;
}
footer { margin-top: 3.5rem; padding-top: 1.25rem; border-top: 1px solid var(--line);
  font-size: .8rem; color: var(--ink-3); }
</style>
</head>
<body>
<div class="wrap">

<header class="top">
  <span class="mark" aria-hidden="true">55</span>
  <h1>Chunking, embeddings, and what overlap costs</h1>
  <p class="lede">
    Three levers decide whether a video RAG index can find the right ten seconds:
    how wide a chunk is, how much of it the next chunk repeats, and which weights encode it.
    Every number on this page was measured on <code>evals/dev</code> by
    <code>make sweep</code> — move a lever and read what happened, rather than what should have.
  </p>
  <div class="prov" id="prov"></div>
</header>

<h2>Move a lever</h2>
<p>
  Both sliders snap to settings that were <em>actually swept</em>. Only a cross through the
  lever space was measured — the window walked at the shipped overlap, the overlap walked at
  the shipped window — so most combinations of the two have no number, and this page says
  “not measured” instead of interpolating one.
</p>

<div class="panel">
  <div class="levers">
    <div class="lever">
      <label for="window">chunk.window_s — how wide a chunk is</label>
      <div class="val" id="window-val">—</div>
      <input type="range" id="window" min="0" max="1" step="1" value="0">
      <div class="ticks" id="window-ticks"></div>
    </div>
    <div class="lever">
      <label for="overlap">chunk.overlap_s — how much the next chunk repeats</label>
      <div class="val" id="overlap-val">—</div>
      <input type="range" id="overlap" min="0" max="1" step="1" value="0">
      <div class="ticks" id="overlap-ticks"></div>
    </div>
  </div>

  <div class="readout" id="readout"></div>
  <div class="note" id="verdict"></div>
</div>

<h2>Chunking vs recall</h2>
<p>
  Overlap held at the shipped value; the window walked from very narrow to very wide. The
  dashed line is the Phase 1 threshold, <strong>recall@5 ≥ 0.80</strong>. Bars are the number
  of chunks the whole dev corpus produced — the thing you pay to embed and store.
</p>
<figure>
  <div id="chart-window"></div>
  <figcaption id="cap-window"></figcaption>
</figure>

<h2>The cost of overlap</h2>
<p>
  Window held at the shipped value; the overlap walked from none to nearly two-thirds of a
  window. Bars here are the <strong>duplication factor</strong> — indexed characters divided
  by transcript characters. 1.00 means every word is stored once; anything above it is the
  same words paid for again.
</p>
<figure>
  <div id="chart-overlap"></div>
  <figcaption id="cap-overlap"></figcaption>
</figure>

<h2>Every point that was measured</h2>
<div class="panel scroll">
  <table id="grid">
    <thead>
      <tr>
        <th>window / overlap</th><th>hop</th><th>chunks</th><th>dup</th>
        <th>max chunk</th><th>&gt;tol</th><th>r@1</th><th>r@3</th><th>r@5</th>
        <th>embed s</th><th>store MB</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>
<p class="mono" style="font-size:.75rem;color:var(--ink-3)">
  <span id="grid-legend"></span>
</p>

<h2>What the three levers actually trade</h2>
<div class="panel">
  <h3>The window trades <em>topical focus</em> against <em>citability</em></h3>
  <p id="lesson-window">—</p>
  <h3>Overlap buys boundary recall with duplicated text</h3>
  <p id="lesson-overlap">—</p>
  <h3>The embedding weights outrank both</h3>
  <p id="lesson-embed">—</p>
</div>

<h2>Recall came back low. Check these, in this order.</h2>
<p>
  Every one of these has produced a wrong number in this repo at least once, and the
  chunker was the first suspect every time. It was the chunker once.
</p>
<ol class="checks">
  <li>
    <strong>Is the embedder the quantisation you think it is?</strong>
    <code>ollama pull hf.co/&lt;repo&gt;</code> with no tag takes the repo's <em>smallest</em>
    file. Here that is <code>Q2_K</code>, and it halved recall@5 relative to
    <code>:F16</code> — a bigger swing than every chunking lever on this page combined.
    <pre>ollama list        # the tag is in the name; :latest is not a version, it is the smallest file</pre>
  </li>
  <li>
    <strong>Is the index one generation of chunks, or two?</strong>
    Chunk ids are <code>&lt;video_id&gt;_&lt;t_start&gt;_&lt;t_end&gt;</code>, so moving a
    lever changes the ids and the old rows stay behind. An index holding both scores better
    than either, for no reason the levers explain.
    <pre>make index-dev INDEX_FLAGS=--reset    # after any chunk lever moves</pre>
  </li>
  <li>
    <strong>What else is in the index?</strong>
    recall@k is a property of the whole store, not of the chunker. Two videos that are not in
    the corpus were added to this repo's <code>./chroma</code> at some point, and the Phase 1
    gate fell from 0.9167 to 0.8333 with no lever touched — 521 extra chunks competing for five
    slots, and the most fragile pair losing its place. Filtered back to the four corpus videos
    it is 0.9167 again.
    <pre>make sources       # every video_id the store actually holds</pre>
  </li>
  <li>
    <strong>Is <code>dev ∩ heldout</code> still empty?</strong>
    No gate result counts until this holds — a number tuned against a question that is also
    in the sealed set is not a measurement of anything.
    <pre>make leakage-check</pre>
  </li>
  <li>
    <strong>Is the miss a wrong video, or the right video at the wrong second?</strong>
    Different bugs. Wrong video is a retrieval problem; right video, wrong second, is almost
    always a chunk wider than the ±30 s citation tolerance. The gate prints which, per pair.
    <pre>make gate-phase1</pre>
  </li>
  <li>
    <strong>Only then, move a window.</strong> One lever, on <code>evals/dev</code>, three
    attempts, then escalate. Never on <code>evals/heldout</code>.
    <pre>make sweep-dry     # what a lever does to the index, in seconds
make sweep         # what it does to recall, in ~20 minutes</pre>
  </li>
</ol>

<h2>How to read these numbers honestly</h2>
<div class="panel">
  <p id="honest-1">—</p>
  <p id="honest-2">—</p>
  <p id="honest-3">—</p>
</div>

<footer>
  Generated by <code>tools/build_coach.py</code> from
  <code>docs/learning/data/chunking_sweep.json</code> — <code>make coach</code> rebuilds it.
  The prose that argues these numbers is
  <a href="primer-chunking-embeddings.md">primer-chunking-embeddings.md</a>.
  No chunk text appears on this page or in the JSON behind it; the corpus is pointers, not
  copies (<code>data/corpus/PROVENANCE.md</code>).
</footer>

</div>

<script type="application/json" id="sweep-data">__SWEEP_JSON__</script>
<script>
"use strict";

const SWEEP = JSON.parse(document.getElementById("sweep-data").textContent);
const PTS = SWEEP.points;
const SHIPPED = SWEEP.shipped;
const THRESHOLD = 0.80;               // the Phase 1 exit criterion, tests/gates/gate_phase1.py

const fmt = (n, d = 2) => (n === null || n === undefined ? "—" : Number(n).toFixed(d));
const g = (n) => (n === null || n === undefined ? "—" : String(Number(n)));

const at = (w, o) => PTS.find((p) => p.levers.window_s === w && p.levers.overlap_s === o) || null;
const windows = [...new Set(PTS.map((p) => p.levers.window_s))].sort((a, b) => a - b);
const overlaps = [...new Set(PTS.map((p) => p.levers.overlap_s))].sort((a, b) => a - b);
const windowCut = PTS.filter((p) => p.levers.overlap_s === SHIPPED.overlap_s)
  .sort((a, b) => a.levers.window_s - b.levers.window_s);
const overlapCut = PTS.filter((p) => p.levers.window_s === SHIPPED.window_s)
  .sort((a, b) => a.levers.overlap_s - b.levers.overlap_s);

// --------------------------------------------------------------------------- provenance

document.getElementById("prov").innerHTML = [
  `k = ${SWEEP.k}`,
  `tolerance ±${g(SWEEP.citation_tolerance_s)}s`,
  `${SWEEP.answerable_pairs} answerable dev pairs`,
  `${SWEEP.dev_videos.length} dev videos`,
  `embed ${SWEEP.embed_model}`,
  `asr arm ${SWEEP.transcript_arm}`,
  `${PTS.length} points in ${g(SWEEP.wall_s)}s`,
  `$${fmt(SWEEP.total_cost_usd, 4)}`,
  `swept ${SWEEP.generated}`,
].map((t) => `<span>${t}</span>`).join("");

// --------------------------------------------------------------------------- the levers

const winInput = document.getElementById("window");
const ovInput = document.getElementById("overlap");
winInput.max = String(windows.length - 1);
ovInput.max = String(overlaps.length - 1);
winInput.value = String(windows.indexOf(SHIPPED.window_s));
ovInput.value = String(overlaps.indexOf(SHIPPED.overlap_s));

const ticks = (el, vals) => {
  el.innerHTML = vals.map((v) => `<span>${g(v)}</span>`).join("");
};
ticks(document.getElementById("window-ticks"), windows);
ticks(document.getElementById("overlap-ticks"), overlaps);

function stat(k, v, note, flag) {
  return `<div class="stat"${flag ? ` data-flag="${flag}"` : ""}>
    <div class="k">${k}</div><div class="v">${v}</div><div class="n">${note || "&nbsp;"}</div>
  </div>`;
}

function render() {
  const w = windows[Number(winInput.value)];
  const o = overlaps[Number(ovInput.value)];
  document.getElementById("window-val").textContent = `${g(w)} s`;
  document.getElementById("overlap-val").textContent = `${g(o)} s`;

  const p = at(w, o);
  const readout = document.getElementById("readout");
  const verdict = document.getElementById("verdict");

  if (!p) {
    /* Two different "no number here" cases, and collapsing them would teach the wrong thing.
       overlap >= window is not an unmeasured point: hop would be <= 0, the grid would never
       advance, and src/config.py raises rather than running it. Only the other case is a gap
       in the sweep. */
    const impossible = o >= w;
    readout.innerHTML = [
      stat("hop", `${g(w - o)} s`, "window − overlap", impossible ? "bad" : null),
      stat("chunks", "—", impossible ? "cannot be built" : "not measured"),
      stat("duplication", "—", impossible ? "cannot be built" : "not measured"),
      stat("recall@5", "—", impossible ? "cannot be built" : "not measured"),
    ].join("");

    if (impossible) {
      verdict.dataset.kind = "unmeasured";
      verdict.innerHTML =
        `<strong>window ${g(w)} s / overlap ${g(o)} s is not a setting, it is an error.</strong> ` +
        `Windows advance by <code>window_s − overlap_s</code>, so a hop of ${g(w - o)} s means ` +
        `the grid never moves and the chunker would not terminate. ` +
        `<code>src/config.py</code> raises on it rather than running it — one of the few places ` +
        `a lever is checked against another lever instead of only against itself.`;
      return;
    }

    verdict.dataset.kind = "unmeasured";
    verdict.innerHTML =
      `<strong>window ${g(w)} s / overlap ${g(o)} s was not swept.</strong> ` +
      `Only the cross through ${g(SHIPPED.window_s)} s / ${g(SHIPPED.overlap_s)} s has ` +
      `numbers, and a recall guessed by interpolating between two grid points is a ` +
      `prediction wearing a measurement's clothes. Add the point to ` +
      `<code>WINDOW_CUT</code>/<code>OVERLAP_CUT</code> in ` +
      `<code>tools/sweep_chunking.py</code> and re-run <code>make sweep</code>.`;
    return;
  }

  const s = p.score, ix = p.index, c = p.counts, sh = p.shape;
  const passes = s.recall_at_5 >= THRESHOLD;
  readout.innerHTML = [
    stat("recall@5", fmt(s.recall_at_5, 4), `${s.hits_at_5}/${s.pairs} pairs`,
         passes ? "good" : "bad"),
    stat("recall@1", fmt(s.recall_at_1, 4), "top result alone"),
    stat("chunks", g(c.chunks), `${g(sh.mean_words_per_chunk)} words each`),
    stat("duplication", `${fmt(c.duplication, 2)}×`,
         `${g(c.words_indexed)} of ${g(c.transcript_words)} words`,
         c.duplication >= 1.6 ? "warn" : null),
    stat("longest chunk", `${fmt(sh.max_chunk_s, 1)} s`,
         `tolerance is ±${g(SWEEP.citation_tolerance_s)} s`,
         sh.max_chunk_s > SWEEP.citation_tolerance_s ? "warn" : "good"),
    stat("uncitable chunks", g(sh.over_tolerance), "wider than the tolerance",
         sh.over_tolerance > 0 ? "warn" : "good"),
    stat("embed time", `${fmt(ix.embed_wall_s, 1)} s`, "4 dev videos, local"),
    stat("store", `${fmt(ix.store_bytes / 1e6, 1)} MB`, "Chroma on disk"),
  ].join("");

  const shipped = p.shipped;
  const parts = [];
  if (shipped) {
    parts.push(
      `<strong>This is the shipped setting.</strong> Phase 1 (VRAG-017) was graded here at ` +
      `recall@5 = ${fmt(s.recall_at_5, 4)}, against a threshold of ${fmt(THRESHOLD, 2)}.`);
  } else {
    const base = at(SHIPPED.window_s, SHIPPED.overlap_s);
    const dr = s.recall_at_5 - base.score.recall_at_5;
    const dc = c.chunks / base.counts.chunks;
    parts.push(
      `Against the shipped ${g(SHIPPED.window_s)} s / ${g(SHIPPED.overlap_s)} s: ` +
      `recall@5 ${dr === 0 ? "unchanged" : (dr > 0 ? "+" : "") + fmt(dr, 4)} ` +
      `(${s.hits_at_5} of ${s.pairs} pairs against ${base.score.hits_at_5}), ` +
      `and ${fmt(dc, 2)}× the chunks to embed and store.`);
  }
  if (!passes) {
    parts.push(`It does <strong>not</strong> clear the Phase 1 threshold of ` +
               `${fmt(THRESHOLD, 2)}.`);
  }
  if (sh.over_tolerance > 0) {
    parts.push(
      `${sh.over_tolerance} chunk${sh.over_tolerance === 1 ? " is" : "s are"} wider than the ` +
      `±${g(SWEEP.citation_tolerance_s)} s citation tolerance, so ` +
      `${sh.over_tolerance === 1 ? "it" : "they"} can retrieve the right passage and still be ` +
      `scored wrong — the citation points at the chunk's start.`);
  }
  const step = 1 / s.pairs;
  parts.push(
    `${s.pairs} answerable pairs, so one pair is ${fmt(step, 4)} of recall: differences ` +
    `smaller than that are not differences.`);

  verdict.dataset.kind = shipped ? "shipped" : "";
  verdict.innerHTML = parts.join(" ");
}

winInput.addEventListener("input", render);
ovInput.addEventListener("input", render);
render();

// --------------------------------------------------------------------------- charts

const NS = "http://www.w3.org/2000/svg";
const el = (name, attrs, text) => {
  const n = document.createElementNS(NS, name);
  for (const [k, v] of Object.entries(attrs || {})) n.setAttribute(k, String(v));
  if (text !== undefined) n.textContent = text;
  return n;
};

/* One chart shape, used twice: bars for the cost, a line for recall@5, a dashed threshold.
   Two y-scales on one frame is normally a way to make any two series look related — here
   the point is precisely that they are not, so both scales are labelled and the bar scale
   starts at its own floor rather than at zero-looks-like-the-line's-zero. */
function chart(host, cut, opts) {
  const W = 720, H = 260, L = 46, R = 52, T = 18, B = 42;
  const iw = W - L - R, ih = H - T - B;
  const svg = el("svg", {viewBox: `0 0 ${W} ${H}`, role: "img", "aria-label": opts.aria});

  const xs = cut.map(opts.x);
  const bars = cut.map(opts.bar);
  const recalls = cut.map((p) => p.score.recall_at_5);
  /* Bars are scaled so the tallest reaches BAR_SHARE of the frame, not the whole of it. The
     recall line on this data sits between 0.83 and 0.92 — the top sixth — so a bar scaled to
     fill the frame puts its value label straight through the line it is meant to sit under.
     This is a layout constant, not a data one: it changes nothing about what is plotted. */
  const BAR_SHARE = 0.62;
  const barFloor = opts.barFloor === undefined ? 0 : opts.barFloor;
  const barMax = barFloor + (Math.max(...bars) - barFloor) / BAR_SHARE;
  // Inset so the first and last points do not sit on top of the axis labels either side.
  const PAD = 14;
  const px = (i) =>
    L + PAD + (cut.length === 1 ? (iw - 2 * PAD) / 2 : (i * (iw - 2 * PAD)) / (cut.length - 1));
  const pyR = (r) => T + ih - (r * ih);                       // recall axis: 0..1, fixed
  const pyB = (v) => T + ih - ((v - barFloor) / (barMax - barFloor)) * ih;

  svg.appendChild(el("line", {class: "chart-axis", x1: L, y1: T + ih, x2: L + iw, y2: T + ih}));

  // Cost bars first, so the recall line sits on top of them.
  const bw = Math.min(34, (iw / cut.length) * 0.5);
  cut.forEach((p, i) => {
    const y = pyB(bars[i]);
    svg.appendChild(el("rect", {
      class: "chart-bar", x: px(i) - bw / 2, y, width: bw, height: Math.max(0, T + ih - y),
      rx: 3,
    }));
    svg.appendChild(el("text", {class: "chart-value", x: px(i), y: y - 5}, opts.barLabel(p)));
  });

  // The threshold every recall number on this page is graded against.
  svg.appendChild(el("line", {
    class: "chart-thresh", x1: L, y1: pyR(THRESHOLD), x2: L + iw, y2: pyR(THRESHOLD),
  }));
  svg.appendChild(el("text", {
    class: "chart-label", x: L + iw + 6, y: pyR(THRESHOLD) + 3,
  }, `${fmt(THRESHOLD, 2)} gate`));

  svg.appendChild(el("polyline", {
    class: "chart-line",
    points: cut.map((p, i) => `${px(i)},${pyR(recalls[i])}`).join(" "),
  }));
  cut.forEach((p, i) => {
    svg.appendChild(el("circle", {
      class: "chart-dot" + (p.shipped ? " shipped" : ""),
      cx: px(i), cy: pyR(recalls[i]), r: p.shipped ? 6 : 4,
    }));
    svg.appendChild(el("text", {
      class: "chart-value", x: px(i), y: pyR(recalls[i]) - 11,
    }, fmt(recalls[i], 2)));
    svg.appendChild(el("text", {
      class: "chart-label", x: px(i), y: T + ih + 16, "text-anchor": "middle",
    }, `${g(xs[i])}`));
  });

  svg.appendChild(el("text", {
    class: "chart-label", x: L + iw / 2, y: H - 8, "text-anchor": "middle",
  }, opts.xLabel));
  [0, 0.5, 1].forEach((r) => {
    svg.appendChild(el("text", {
      class: "chart-label", x: L - 8, y: pyR(r) + 3, "text-anchor": "end",
    }, fmt(r, 1)));
  });
  // Axis titles sit a line clear of the topmost tick label (which is at y = T).
  svg.appendChild(el("text", {
    class: "chart-label", x: L - 8, y: T - 12, "text-anchor": "end",
  }, "recall@5"));
  svg.appendChild(el("text", {
    class: "chart-label", x: L + iw + 6, y: T - 12,
  }, opts.barAxis));

  host.appendChild(svg);
}

chart(document.getElementById("chart-window"), windowCut, {
  aria: "recall@5 and chunk count against chunk window width",
  x: (p) => p.levers.window_s,
  xLabel: `chunk.window_s (seconds) — overlap pinned at ${g(SHIPPED.overlap_s)} s`,
  bar: (p) => p.counts.chunks,
  barLabel: (p) => g(p.counts.chunks),
  barAxis: "chunks",
});

chart(document.getElementById("chart-overlap"), overlapCut, {
  aria: "recall@5 and duplication factor against chunk overlap",
  x: (p) => p.levers.overlap_s,
  xLabel: `chunk.overlap_s (seconds) — window pinned at ${g(SHIPPED.window_s)} s`,
  bar: (p) => p.counts.duplication,
  barFloor: 1,
  barLabel: (p) => `${fmt(p.counts.duplication, 2)}×`,
  barAxis: "duplication",
});

// --------------------------------------------------------------------------- the table

const tbody = document.querySelector("#grid tbody");
const ordered = [...windowCut, ...overlapCut.filter((p) => !p.shipped)];
tbody.innerHTML = ordered.map((p) => {
  const lv = p.levers, c = p.counts, sh = p.shape, s = p.score, ix = p.index;
  const cut = lv.overlap_s === SHIPPED.overlap_s ? "window" : "overlap";
  return `<tr data-shipped="${p.shipped ? 1 : 0}" data-cut="${cut}">
    <td>${g(lv.window_s)} / ${g(lv.overlap_s)}${p.shipped ? " ◂ shipped" : ""}</td>
    <td>${g(lv.hop_s)}</td><td>${g(c.chunks)}</td><td>${fmt(c.duplication, 2)}</td>
    <td>${fmt(sh.max_chunk_s, 1)}</td><td>${g(sh.over_tolerance)}</td>
    <td>${fmt(s.recall_at_1, 2)}</td><td>${fmt(s.recall_at_3, 2)}</td>
    <td><strong>${fmt(s.recall_at_5, 4)}</strong></td>
    <td>${fmt(ix.embed_wall_s, 1)}</td><td>${fmt(ix.store_bytes / 1e6, 1)}</td>
  </tr>`;
}).join("");

document.getElementById("grid-legend").textContent =
  `${ordered.length} points · rows above the shipped row walk the window at overlap = ` +
  `${g(SHIPPED.overlap_s)} s; rows below walk the overlap at window = ` +
  `${g(SHIPPED.window_s)} s · >tol = chunks longer than the ±` +
  `${g(SWEEP.citation_tolerance_s)} s citation tolerance`;

// --------------------------------------------------------------------------- the lessons

/* "the best setting" is a phrase this data does not support, so it is not used. Six of the
   seven windows return the identical recall@5, and on 12 pairs a tie is a tie — naming a
   winner among them would be reading rank off measurement noise. topOf() reports how many
   settings share the maximum instead. */
const topOf = (rows) => {
  const max = Math.max(...rows.map((p) => p.score.recall_at_5));
  return {max, tied: rows.filter((p) => p.score.recall_at_5 === max)};
};
const shippedPt = at(SHIPPED.window_s, SHIPPED.overlap_s);
const widest = windowCut[windowCut.length - 1];
const narrowest = windowCut[0];
const noOverlap = overlapCut[0];
const mostOverlap = overlapCut[overlapCut.length - 1];
const topWindow = topOf(windowCut);
/* The miss that overlap = 0 introduces, in seconds off the reference. Read out of the run
   rather than written down: if a re-sweep moves it, the sentence below moves with it. */
const zeroOverlapMiss = Math.max(
  ...noOverlap.score.rows.filter((r) => r.hit_rank === null && r.nearest_dt_s !== null)
    .map((r) => r.nearest_dt_s)
    .filter((dt) => dt < 60)          // d010 misses at every setting by ~10 minutes; not this
);
const list = (rows, key) => rows.map((p) => `${g(p.levers[key])}`).join(", ");

document.getElementById("lesson-window").innerHTML =
  `A narrow window is a tight topic and a precise citation; a wide one carries more context ` +
  `per vector but blurs what the vector is about, and — the part that is specific to video — ` +
  `pushes the chunk's start further from the moment it describes. At ` +
  `${g(narrowest.levers.window_s)} s the dev corpus becomes ${g(narrowest.counts.chunks)} ` +
  `chunks and scores ${fmt(narrowest.score.recall_at_5, 4)}; at ` +
  `${g(widest.levers.window_s)} s it is ${g(widest.counts.chunks)} chunks scoring ` +
  `${fmt(widest.score.recall_at_5, 4)}, with ${g(widest.shape.over_tolerance)} of them wider ` +
  `than the citation tolerance. What the middle of the range does <em>not</em> show is a ` +
  `peak: ${topWindow.tied.length} of the ${windowCut.length} windows measured — ` +
  `${list(topWindow.tied, "window_s")} s — return the identical ` +
  `${fmt(topWindow.max, 4)}, and only ${g(widest.levers.window_s)} s is worse. On this dev ` +
  `set the window is not a tuning lever; it is a constraint to satisfy.`;

document.getElementById("lesson-overlap").innerHTML =
  `Overlap exists for one failure: a sentence cut in half by a window boundary, present in ` +
  `two chunks and whole in neither. It fixes that by writing the corpus into the index more ` +
  `than once. With no overlap at all the dev corpus is ${g(noOverlap.counts.chunks)} chunks ` +
  `at ${fmt(noOverlap.counts.duplication, 2)}× duplication and recall@5 = ` +
  `${fmt(noOverlap.score.recall_at_5, 4)}; at ${g(mostOverlap.levers.overlap_s)} s it is ` +
  `${g(mostOverlap.counts.chunks)} chunks at ${fmt(mostOverlap.counts.duplication, 2)}× and ` +
  `${fmt(mostOverlap.score.recall_at_5, 4)}. The shipped ${g(SHIPPED.overlap_s)} s sits at ` +
  `${fmt(shippedPt.counts.duplication, 2)}× — ` +
  `${fmt((shippedPt.counts.duplication - 1) * 100, 0)}% of the embedding bill is text the ` +
  `index already holds.` +
  `<br><br>The whole visible benefit of overlap on this set is <strong>one pair</strong>, ` +
  `and it is worth knowing which. At 0 s, <code>d003</code> misses: the nearest result from ` +
  `the right video starts ${fmt(zeroOverlapMiss, 1)} s from the reference, against a ` +
  `tolerance of ${g(SWEEP.citation_tolerance_s)} s. It is over the line by ` +
  `${fmt(zeroOverlapMiss - SWEEP.citation_tolerance_s, 1)} s — a boundary landing in the ` +
  `wrong place, which is precisely the failure overlap exists to buy off. Every overlap from ` +
  `${g(overlapCut[1].levers.overlap_s)} s up recovers it and none of them recovers anything ` +
  `else, so this lever bought ${fmt(1 / SWEEP.answerable_pairs, 4)} of recall for ` +
  `${fmt(shippedPt.counts.duplication / noOverlap.counts.duplication, 2)}× the tokens.`;

document.getElementById("lesson-embed").innerHTML =
  `Across this whole grid recall@5 moves between ` +
  `${fmt(Math.min(...PTS.map((p) => p.score.recall_at_5)), 4)} and ` +
  `${fmt(Math.max(...PTS.map((p) => p.score.recall_at_5)), 4)}. Swapping the same model's ` +
  `weights from <code>Q2_K</code> to <code>:F16</code> — one tag on one ` +
  `<code>ollama pull</code>, 225 MB — moved it 0.4167 → 0.9167 (VRAG-017, in the README). ` +
  `The encoder is the first thing to check and the last thing to tune, because it is the ` +
  `only lever here that changes what “similar” means.`;

// ------------------------------------------------------------------- reading them honestly

const spend = SWEEP.total_cost_usd;
document.getElementById("honest-1").innerHTML =
  `<strong>${SWEEP.answerable_pairs} pairs is a coarse ruler.</strong> One pair is ` +
  `${fmt(1 / SWEEP.answerable_pairs, 4)} of recall, so every number on this page moves in ` +
  `steps that size. Two settings separated by one pair are not ranked by this measurement; ` +
  `they are tied, and the tie-break has to be something else — chunk citability, index size, ` +
  `embedding time.`;

document.getElementById("honest-2").innerHTML =
  `<strong>The dollar cost of overlap is $${fmt(spend, 4)}, and that is an artefact of ` +
  `running locally.</strong> ${PTS.length} points, ` +
  `${g(PTS.reduce((n, p) => n + p.counts.chunks, 0))} chunks embedded, ` +
  `$0.00 — <code>nomic-ai/nomic-embed-text-v1.5-GGUF:F16</code> is rated at zero in ` +
  `<code>src/telemetry.py</code> because it runs on this machine. What overlap really costs ` +
  `is visible in the other three columns: tokens, seconds, and megabytes. Move the embedder ` +
  `to a metered endpoint and the duplication factor becomes the multiplier on the invoice ` +
  `directly — ${fmt(shippedPt.counts.duplication, 2)}× at the shipped setting.`;

document.getElementById("honest-3").innerHTML =
  `<strong>This grid is a lookup table for one ASR arm.</strong> The chunk-duration ceiling ` +
  `depends on how long the transcriber's segments run, because segments are never split and ` +
  `a chunk overhangs its window at both ends. These points were measured on the ` +
  `<code>${SWEEP.transcript_arm}</code> arm; change the arm and the “uncitable chunks” ` +
  `column has to be re-measured before any of it can be quoted.`;
</script>
</body>
</html>
"""


def main() -> int:
    if not SWEEP.is_file():
        raise SystemExit(f"{SWEEP} not found — run `make sweep` first.")

    payload = json.loads(SWEEP.read_text(encoding="utf-8"))
    if payload.get("dry_run"):
        raise SystemExit(
            f"{SWEEP} is a --dry-run sweep: it has chunk counts but no recall. "
            f"The coach page is mostly recall, so build it from a full `make sweep`."
        )

    # When the measurements were taken. Read off the file rather than stamped at build time:
    # rebuilding the page does not re-measure anything, and a build-time date on a page of
    # last month's numbers is the kind of tidy-looking wrong this repo keeps finding.
    stamped = dt.datetime.fromtimestamp(SWEEP.stat().st_mtime).strftime("%Y-%m-%d")
    payload["generated"] = stamped

    blob = json.dumps(payload, separators=(",", ":"))
    # `</script>` inside the JSON would close the block early; the escape is inert in JSON.
    blob = blob.replace("</", "<\\/")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(TEMPLATE.replace("__SWEEP_JSON__", blob), encoding="utf-8")

    kb = OUT.stat().st_size / 1024
    print(
        f"wrote {OUT.relative_to(ROOT).as_posix()} — {kb:.0f} KB, "
        f"{len(payload['points'])} points, swept {stamped}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
